### ISSUE TITLE
Pre-trained weights

### ISSUE THREAD

**Issue by mcljtkim** [RuoyuChen10/Privacy_Enhancing_Face_Obfuscation#1]
Can you please share the pre-trained weights by the Google Drive?

I cannot access to the Baidu, so I cannot play the experiments.

**Comment by RuoyuChen10** [comment]
> Can you please share the pre-trained weights by the Google Drive?
> 
> I cannot access to the Baidu, so I cannot play the experiments.

I do not have any space on Google Driver, can you offer me your email? I will send the files to you.

**Comment by mcljtkim** [comment]
I would appreciate it if you could kindly send the document to the following email address: 
jtkim@mcl.korea.ac.kr.

Thank you for your assistance.

**Comment by RuoyuChen10** [comment]
> I would appreciate it if you could kindly send the document to the following email address: [jtkim@mcl.korea.ac.kr](mailto:jtkim@mcl.korea.ac.kr).
> 
> Thank you for your assistance.

I have sent the file to you, pay attention to your e-mail, including your junk mailbox.
